import type { HigherEducationIndustryContent } from "@/components/industry/narratives/industry-narrative-types";

const imageBase = "/images/industries/higher-education";

export const higherEducationIndustryContent = {
  sector: "ensino-superior",
  metadata: {
    title: "Privacidade para instituições de ensino superior | TOGETHER",
    description: "Estruture dados, bases legais, áreas, terceiros, respostas e capacitação com a TOGETHER.",
    canonical: "/solucoes/privacidade-ensino-superior",
    socialAlt: "Estudantes adultos e professor em operação acadêmica contemporânea",
  },
  hero: {
    pill: "Privacidade para o ensino superior",
    title: "Estruture a privacidade da sua instituição,",
    accent: "dos dados à rotina das pessoas.",
    description: "A TOGETHER ajuda sua instituição a organizar dados, decisões, fornecedores, procedimentos e capacitação para que a privacidade funcione na prática.",
    cta: "Agendar uma conversa",
    trustLine: "Experiência da TOGETHER em privacidade, tecnologia e operação.",
    secondaryCta: { label: "Conhecer as seis frentes", href: "#seis-frentes" },
    image: {
      desktop: { avif: `${imageBase}/hero-desktop.avif`, webp: `${imageBase}/hero-desktop.webp`, png: `${imageBase}/hero-desktop.png`, width: 1672, height: 941 },
      mobile: { avif: `${imageBase}/hero-mobile.avif`, webp: `${imageBase}/hero-mobile.webp`, png: `${imageBase}/hero-mobile.png`, width: 941, height: 1672 },
    },
  },
  narrative: {
    context: {
      id: "programa-de-privacidade",
      pill: "Privacidade na prática",
      title: "Sua instituição precisa de um programa de privacidade",
      accent: "que englobe dados, sistemas, contratos e pessoas.",
      description: "Somente políticas de privacidade não organizam sozinhas onde os dados estão, por que são utilizados, quem pode acessá-los ou como agir diante de uma solicitação ou incidente.",
      note: "Por isso, a TOGETHER trabalha seis frentes que se complementam e precisam evoluir com a instituição.",
    },
    sixFronts: {
      id: "seis-frentes",
      pill: "As seis frentes",
      title: "Privacidade exige critérios claros",
      accent: "e procedimentos que funcionem.",
      description: "Estas frentes atuam juntas e evoluem com a instituição. A TOGETHER ajuda a estruturar cada uma conforme as prioridades e o escopo do trabalho.",
      items: [
        {
          icon: "route",
          label: "01",
          title: "Mapeamento de dados, sistemas e fluxos",
          description: "Identifique quais dados a instituição utiliza, onde estão armazenados, por quais sistemas circulam e quais fornecedores participam do tratamento.",
          togetherHelp: "A TOGETHER conduz o levantamento com as áreas envolvidas e organiza uma visão dos fluxos conforme o escopo do projeto.",
        },
        {
          icon: "file",
          label: "02",
          title: "Finalidade, base legal, acesso e retenção",
          description: "Defina por que cada dado é utilizado, qual base legal sustenta o tratamento, quem precisa de acesso e por quanto tempo a informação deve ser mantida.",
          togetherHelp: "A TOGETHER apoia a definição e a documentação de critérios que possam ser aplicados na operação da instituição.",
        },
        {
          icon: "users",
          label: "03",
          title: "Governança integrada entre as áreas",
          description: "Conecte Jurídico, TI, Segurança da Informação, Contratos e áreas acadêmicas nas decisões que envolvem dados pessoais.",
          togetherHelp: "A TOGETHER ajuda a definir responsáveis, fluxos de decisão e pontos de acompanhamento entre as áreas.",
        },
        {
          icon: "network",
          label: "04",
          title: "Governança de terceiros",
          description: "Avalie fornecedores, estabeleça responsabilidades contratuais e acompanhe acessos e medidas de proteção durante toda a relação.",
          togetherHelp: "A TOGETHER estrutura critérios para avaliação, contratação, monitoramento e encerramento da relação com terceiros.",
        },
        {
          icon: "shield",
          label: "05",
          title: "Direitos dos titulares e resposta a incidentes",
          description: "Crie canais, responsáveis, registros e etapas para atender titulares e responder a incidentes de segurança e privacidade.",
          togetherHelp: "A TOGETHER transforma as obrigações em procedimentos que as equipes conseguem executar, acompanhar e registrar.",
        },
        {
          icon: "presentation",
          label: "06",
          title: "Capacitação e cultura de privacidade",
          description: "Prepare professores, funcionários e gestores de acordo com as responsabilidades e situações vividas por cada função.",
          togetherHelp: "A TOGETHER desenvolve ações contínuas de conscientização e capacitação conectadas aos procedimentos implantados.",
        },
      ],
    },
    togetherApproach: {
      id: "como-a-together-atua",
      pill: "Como a TOGETHER atua",
      title: "Da prioridade à implantação,",
      accent: "com acompanhamento contínuo.",
      description: "A TOGETHER começa com um diagnóstico da realidade da instituição e pode priorizar as frentes que exigem resposta primeiro.",
      items: [
        { icon: "analytics", label: "01", title: "Diagnosticar", description: "Entender o contexto, as prioridades e o nível de estrutura já existente." },
        { icon: "route", label: "02", title: "Planejar", description: "Definir escopo, responsáveis e prioridades para organizar a implantação." },
        { icon: "check", label: "03", title: "Implantar", description: "Construir critérios, procedimentos, registros e capacitações previstos no projeto." },
        { icon: "users", label: "04", title: "Acompanhar", description: "Revisar a aplicação e apoiar a evolução contínua das frentes contratadas." },
      ],
      cta: {
        eyebrow: "Próximo passo",
        title: "Leve as prioridades da instituição para um plano de ação.",
        description: "Converse com a TOGETHER para identificar o ponto de partida e o escopo mais adequado.",
        label: "Agendar uma conversa",
        href: "#cta",
      },
    },
    outcomes: {
      id: "resultados-na-pratica",
      pill: "O que muda na prática",
      title: "A instituição ganha clareza",
      accent: "para decidir, executar e responder.",
      description: "O resultado é uma operação mais organizada, com critérios conhecidos e responsabilidades que não dependem de improviso.",
      items: [
        { icon: "route", label: "Visão", title: "Dados e fluxos mapeados", description: "A instituição entende onde os dados estão, por onde circulam e quem participa do tratamento." },
        { icon: "file", label: "Critérios", title: "Uso e retenção definidos", description: "Finalidade, base legal, acesso e prazo de retenção orientam as decisões." },
        { icon: "users", label: "Integração", title: "Responsáveis conectados", description: "As áreas sabem quando decidir, executar, apoiar ou ser informadas." },
        { icon: "network", label: "Terceiros", title: "Fornecedores acompanhados", description: "Contratação, acesso, monitoramento e encerramento seguem critérios definidos." },
        { icon: "shield", label: "Resposta", title: "Procedimentos executáveis", description: "Titulares e incidentes seguem canais, responsáveis, registros e etapas conhecidas." },
        { icon: "presentation", label: "Cultura", title: "Equipes preparadas", description: "Professores, funcionários e gestores reconhecem suas responsabilidades na rotina." },
      ],
    },
  },
  faq: {
    pill: "Perguntas frequentes",
    title: "Antes de começar,",
    accent: "entenda como funciona.",
    description: "Respostas sobre as seis frentes, o ponto de partida e a definição do escopo.",
    items: [
      { question: "Preciso implantar as seis frentes ao mesmo tempo?", answer: "Não. As frentes funcionam de forma integrada, mas a implantação pode começar pelas prioridades da instituição e avançar conforme o escopo definido." },
      { question: "Como a TOGETHER inicia o mapeamento de dados?", answer: "A TOGETHER conversa com as áreas que conhecem a operação e identifica dados, atividades, sistemas, compartilhamentos e fornecedores envolvidos no escopo." },
      { question: "O que significa definir finalidade, base legal e retenção?", answer: "Significa esclarecer por que o dado é utilizado, qual fundamento autoriza o tratamento, quem precisa acessá-lo e por quanto tempo ele deve ser mantido." },
      { question: "Como funciona a governança de terceiros?", answer: "Ela organiza critérios para avaliar, contratar, conceder acesso, acompanhar e encerrar relações com fornecedores que tratam dados pessoais." },
      { question: "A TOGETHER ajuda com titulares e incidentes?", answer: "Sim, dentro do escopo contratado. A TOGETHER estrutura canais, responsabilidades, registros e etapas para que as equipes saibam receber, analisar e responder cada situação." },
      { question: "Como funciona a capacitação contínua?", answer: "Os conteúdos são conectados às responsabilidades e situações vividas por professores, funcionários e gestores, com formato e frequência definidos no projeto." },
      { question: "O que acontece na primeira conversa?", answer: "A TOGETHER entende o cenário da instituição, identifica as frentes prioritárias e explica como pode apoiar a implantação." },
      { question: "Como são definidos escopo e investimento?", answer: "Depois de entender as prioridades, as frentes envolvidas, a complexidade da operação e o nível de apoio necessário para a implantação." },
    ],
  },
  finalCta: {
    pill: "Próximo passo",
    title: "Comece pela realidade da sua instituição.",
    description: "Na primeira conversa, a TOGETHER entende o cenário, identifica prioridades e avalia o escopo mais adequado para estruturar o programa de privacidade.",
    cta: "Agendar uma conversa",
    nextStep: "Descubra quais frentes precisam avançar primeiro.",
  },
  campaignAnchors: [
    { id: "admissao", sectionKey: "six-fronts" },
    { id: "ead", sectionKey: "six-fronts" },
    { id: "pesquisa", sectionKey: "six-fronts" },
    { id: "fornecedores", sectionKey: "six-fronts" },
    { id: "incidentes", sectionKey: "six-fronts" },
    { id: "workshops", sectionKey: "six-fronts" },
  ],
  sources: [
    { claim: "Princípios, direitos, segurança e bases da LGPD", url: "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709compilado.htm", reviewedAt: "2026-08-27" },
    { claim: "Dados e metodologia do Censo da Educação Superior", url: "https://www.gov.br/inep/pt-br/areas-de-atuacao/pesquisas-estatisticas-e-indicadores/censo-da-educacao-superior", reviewedAt: "2026-08-27" },
    { claim: "Cadastro nacional e consulta e-MEC", url: "https://www.gov.br/mec/pt-br/politica-regulacao-supervisao-educacao-superior/cadastro-nacional-de-cursos-e-ies", reviewedAt: "2026-08-27" },
    { claim: "Tratamento de dados para fins acadêmicos e pesquisas", url: "https://www.gov.br/anpd/pt-br/centrais-de-conteudo/materiais-educativos-e-publicacoes/guia-orientativo-tratamento-de-dados-pessoais-para-fins-academicos-e-para-a-realizacao-de-estudos-e-pesquisas", reviewedAt: "2026-08-27" },
    { claim: "Comunicação de incidente de segurança", url: "https://www.gov.br/anpd/pt-br/canais_atendimento/agente-de-tratamento/comunicado-de-incidente-de-seguranca-cis", reviewedAt: "2026-08-27" },
  ],
} as const satisfies HigherEducationIndustryContent;
